development:
  adapter: postgresql
  database: labs_pong_tournament_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: labs_pong_tournament_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: labs_pong_tournament_production
  pool: 5
  timeout: 5000
